sudo: false

language: php

cache:
  directories:
    - $HOME/.composer/cache

php:
 - 7.2
 - nightly

env:
  global:
    - EXECUTE_CS_CHECK=false
    - TEST_COVERAGE=false
  matrix:
    - DEPENDENCIES="--prefer-lowest --prefer-stable"
    - DEPENDENCIES=""

matrix:
  allow_failures:
   - php: nightly
  fast_finish: true
  include:
    - php: 7.2
      env: DEPENDENCIES="" EXECUTE_CS_CHECK=true TEST_COVERAGE=true
  exclude:
    - php: 7.2
      env: DEPENDENCIES=""

before_install:
  - phpenv config-rm xdebug.ini || return 0

install:
  - travis_retry composer update --no-interaction --prefer-dist $DEPENDENCIES
  - composer info -i

script:
  - vendor/bin/phpunit
  - vendor/bin/phpspec run
  - vendor/bin/phpstan analyse -l 7 -c phpstan.neoun src
  - vendor/bin/phpcs --standard=resources/phpcs/specs.xml spec tests
  - vendor/bin/phpcs --standard=resources/phpcs/src.xml src
  - vendor/bin/phpcs --standard=resources/phpcs/object-calisthenics.xml src
